### ISSUE TITLE
Customizing transformers 

### ISSUE THREAD

**Issue by yyoncho** [yyoncho/helm-icons#1]
Hi @thierryvolpiatto . I am looking for some guidance on how is the best way to customize helm transformers to add icons(refer to the README gif how it looks like). For sources that are created lazily, I am using `helm-setup-user-source` (e. g. helm-buffers-source) and for some sources, I directly modify the source since it is not created lazily(e. g. helm-source-recentf).

I haven't found a way to update the functions that create the sources inline(e. g. helm-locate-library). Is there a better way to do what I am trying to achieve?

**Comment by thierryvolpiatto** [comment]
Ivan Yonchovski <notifications@github.com> writes:

> Hi @thierryvolpiatto . I am looking for some guidance on how is the
> best way to customize helm transformers to add icons(refer to the
> README gif how it looks like). For sources that are created lazily, I
> am using helm-setup-user-source (e. g. helm-buffers-source) and for
> some sources, I directly modify the source since it is not created
> lazily(e. g. helm-source-recentf).

You can also use helm-setup-user-source for such source.

> I haven't found a way to update the functions that create the sources
> inline(e. g. helm-locate-library).

There is no ways to modify such source, we need to define a class and
run (helm-make-source "foo" 'foo-class ...) to allow using
helm-setup-user-source.
If you have a list of commands that define source inline you want to
modify, let me know I will build classes so that you can modify
them.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by yyoncho** [comment]
> You can also use helm-setup-user-source for such source.

when I do
```
    (cl-defmethod helm-setup-user-source :after ((source helm-not-loaded-source)))
```
I get Debugger entered--Lisp error: (error "Unknown specializer helm-not-loaded-source")
  signal(error ("Unknown specializer helm-not-loaded-source"))
  error("Unknown specializer %S" helm-not-loaded-source)


> If you have a list of commands that define source inline you want to
modify, let me know I will build classes so that you can modify
them.

**Comment by yyoncho** [comment]
> You can also use helm-setup-user-source for such source.

when I do
```
    (cl-defmethod helm-setup-user-source :after ((source helm-not-loaded-source)))
```
I get
```
 Debugger entered--Lisp error: (error "Unknown specializer helm-not-loaded-source")
  signal(error ("Unknown specializer helm-not-loaded-source"))
  error("Unknown specializer %S" helm-not-loaded-source)
```
> If you have a list of commands that define source inline you want to
modify, let me know I will build classes so that you can modify
them.

I will come back with a list.

**Comment by thierryvolpiatto** [comment]
Ivan Yonchovski <notifications@github.com> writes:

>     You can also use helm-setup-user-source for such source.
>    
> when I do
>
>     (cl-defmethod helm-setup-user-source :after ((source helm-not-loaded-source)))
>
> I get Debugger entered--Lisp error: (error "Unknown specializer helm-not-loaded-source")
> signal(error ("Unknown specializer helm-not-loaded-source"))
> error("Unknown specializer %S" helm-not-loaded-source)

Hmm! Don't know. If I eval this I have the same error, but it is normal
as helm-not-loaded-source is not a valid class.
With recentf, there is may be a problem as the source is initialized at
load time by a defcustom, so may be your defmethod is not already known
at this time. This can be fixed if needed.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by yyoncho** [comment]
> With recentf, there is may be a problem as the source is initialized at
load time by a defcustom, so may be your defmethod is not already known
at this time. This can be fixed if needed.

Yes - this is what I was referring to. 

As a side note, what about adding an extension point just before the source has been used? It will make enabling and disabling much easier and won't(?) require reworking places which do not define classes. WDYT?

**Comment by thierryvolpiatto** [comment]
Ivan Yonchovski <notifications@github.com> writes:

>     With recentf, there is may be a problem as the source is initialized at
>     load time by a defcustom, so may be your defmethod is not already known
>     at this time. This can be fixed if needed.
>    
> Yes - this is what I was referring to.
>
> As a side note, what about adding an extension point just before the
> source has been used? It will make enabling and disabling much easier
> and won't(?) require reworking places which do not define
> classes. WDYT?

Sorry I don't understand what you want to do here.



-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by yyoncho** [comment]
@thierryvolpiatto please ignore - I decided to put advice over helm-make-source which solved all of my issues.
