### ISSUE TITLE
Some errors with icons

### ISSUE THREAD

**Issue by deb75** [yyoncho/helm-icons#14]
Hello,

Thanks for this nice package.

I am using emacs 28.0.50 feature/native-comp.

All was working well before I upgraded melpa packages.

Here is my config : 
```lisp
(helm-icons-enable)
;;(setq helm-icons-provider 'all-the-icons)

(use-package helm
  :init
  (setq helm-autoresize-max-height 20)
  (setq helm-buffer-max-length 40)
  :bind
  ("M-x" . helm-M-x)
  ("C-q" . helm-imenu)
  ("C-x C-f" . #'helm-find-files)
  ("C-x b" . #'helm-buffers-list)
  ("C-x r b" . #'helm-filtered-bookmarks)
  ("C-s" . #'swiper-helm)
  )

(require 'helm-config)
(helm-mode 1)

(define-key helm-map (kbd "<left>") 'helm-previous-source)
(define-key helm-map (kbd "<right>") 'helm-next-source)
(customize-set-variable 'helm-ff-lynx-style-map t)
(customize-set-variable 'helm-imenu-lynx-style-map t)
```

Each time I want to use helm commands I get the error message : 
```
helm-icons--get-icon: Invalid function: treemacs-get-icon-value
```
and nothing shows up. although the treemacs config is loaded before helm config (as above).

If I decide to use `all-the-icons`, `helm-buffers` works again with icons but `helm-find-files` returns : 
```
Wrong type argument: sequencep, dir-closed
```

**Comment by elken** [comment]
> If I decide to use all-the-icons, helm-buffers works again with icons but helm-find-files returns :

I have a PR to fix this ^^

I have identified the other issue with treemacs and will add fixes to that after work tonight ^^ Apologies

**Comment by yyoncho** [comment]
should be fixed with https://github.com/yyoncho/helm-icons/pull/13

**Comment by elken** [comment]
There's another problem with treemacs still, I will fix later 😁

**Comment by deb75** [comment]
Thanks !

A few clarifications,  the `treemacs-get-icon-file` bug appears both on linux and windows (10) with emacs 28.0.50 branch. It does not happen with latest emacs 27.1 compiled source. So, it is probably a compatibility issue.

Regards

**Comment by elken** [comment]
Thanks for the feedback, that's a weird one. I will look into it regardless.

For now, the `all-the-icons` stuff should be fine now, do let me know 😁

**Comment by elken** [comment]
@deb75 I have another PR, if you could test it and let me know if this resolves it for you :D

**Comment by deb75** [comment]
@elken I have just upgraded the package `helm-icons`, probably your other PR is not yet in it.

`helm-find-files` does work again ! However, I noticed that `helm-buffers` works but not with the right icon for the right file. As an example, if I open a `*.java` file with `helm-find-files` I get the so called java icon. Then, if I list buffers with `helm-buffers`, it is no more the aformentioned java icon, it looks like the default icon.

That is to note also I configured `treemacs` to use `all-the-icons` :
```
(require 'treemacs-all-the-icons)
(treemacs-load-theme "all-the-icons")
```
and icons displayed are often not the same as `helm-buffers` and `helm-find-files` .

**Comment by elken** [comment]
I haven't tested with that package, seems like a roundabout way. Which provider works then?

**Comment by deb75** [comment]
I have just tested your pull request. I did it by hand and provided no errors from me, I still get `Invalid function : treemacs-get-icon-value`.

I googled this error, it seems be due to the fact that `treemacs-get-icon-file` is a macro, not a real function. So, probably that it does not play well with native compilation (gccemacs)

For now, `all-the-icons` works but with some caveats (not the right icons).

Regards

**Comment by elken** [comment]
I'm running on 28,  currently HEAD so I'm having difficulty replicating this on my end

**Comment by deb75** [comment]
Do you mean the `treemacs-get-icon-file` issue or that some icons are not displayed in `helm-buffers` with `all-the-icons` ?

My branch is not HEAD, will try with HEAD.

**Comment by deb75** [comment]
I still get the `treemacs-get-icons-file` issue with latest emacs 280.0.50 (feature/native-comp) and latest melpa packages.

Also, I pay attention to load  `treemacs` configuration before `helm` one. The curious thing is that `treemacs` works flawlessly with `all-the-icons`, I should also get the same issue with `treemacs`, shouldn't I ?

**Comment by elken** [comment]
Still not able to replicate this. If you can consistently replicate it on as vanilla an emacs as you can and put the steps here I will see if I can fix it.

**Comment by jeffpollock9** [comment]
if at all useful, I am also getting `Invalid function : treemacs-get-icon-value` on emacs 27.1 after upgrading all packages.
