### ISSUE TITLE
Spacemacs layer?

### ISSUE THREAD

**Issue by picandocodigo** [yyoncho/helm-icons#3]
This package is great!

I see you're using Spacemacs, do you have plans on turning this into a Spacemacs layer and if so is there anything I can do to help out? I tried creating a layer locally, but I was unable to make it work. My elisp knowledge is pretty limited...

I created a `helm-treemacs-icons` layer in `~/.emacs.d/private` with `config.el` and `packages.el` files. In `packages.el`, I added:

```elisp
(defconst helm-treemacs-icons-packages
  '(
    (helm-treemacs-icons :local (recipe
                                 :fetcher github
                                 :repo "yyoncho/helm-treemacs-icons/"))
    )

;; Before the end of the file:
(defun helm-treemacs-icons/init-helm-treemacs-icons())
```

And `config.el`:
```elisp
(helm-treemacs-icons-enable)
```

I then added this layer to `dotspacemacs-configuration-layers` in my dot spacemacs file. However I would always get an error.

The way I made it work so far is cloning the repo to `~/.emacs.d/private` and then adding these lines to my `.spacemacs` file:

```elisp
  (load-file "~/.emacs.d/private/helm-treemacs-icons/helm-treemacs-icons.el")
  (require 'helm-treemacs-icons)
  (helm-treemacs-icons-enable)
```

**Comment by yyoncho** [comment]
I plan to add it as part of treemacs layer so if spacemacs maintainers accept it it will be added soon.

**Comment by picandocodigo** [comment]
That's great, thanks!
