### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by fleimgruber** [yyoncho/helm-icons#4]
On Windows the icons are not shown properly. The icons are placed and spaced correctly, but displayed as empty squares. This is most likely to be solved outside of `helm-treemacs-icons`, I just wanted to raise the issue here to think about docs pointers to possible solutions and to make clear which machinery is used for that under the hood.

**Comment by yyoncho** [comment]
Do they work fine in treemacs?

**Comment by fleimgruber** [comment]
Just tried, no, they don't work in treemacs. Will look through issues and for information there. Thanks for the shove.
