### ISSUE TITLE
helm-treemacs-icons breaks helm-mark-all in helm selection windows

### ISSUE THREAD

**Issue by benotn** [yyoncho/helm-icons#5]
When I call `helm-mini` or `helm-find-files`, and I try to mark all candidates with `helm-mark-all` (keybinding "M-a"), I get an error: 

```
Debugger entered--Lisp error: (wrong-type-argument stringp (image :type png :file "/home/ben/.config/emacs/elpa/treemacs-20200419.1220/icons/default/emacs.png" :scale 1 :ascent center :background "#002b36"))
  helm-mark-all-1(t)
  helm-mark-all(nil)
  funcall-interactively(helm-mark-all nil)
  call-interactively(helm-mark-all nil nil)
  command-execute(helm-mark-all)
  read-from-minibuffer(#("pattern: " 0 9 (face helm-minibuffer-prompt)) nil (keymap (33554440 . describe-key) (26 . helm-select-action) (normal-state keymap "Auxiliary keymap for Normal state" (32 . helm-toggle-visible-mark) (121 keymap (121 . helm-kill-selection-and-quit) (80 . helm-copy-to-buffer) (112 . helm-yank-selection)) (47 . helm-quit-and-find-file) (71 . helm-end-of-buffer) (107 . helm-previous-line) (106 . helm-next-line) (41 . helm-next-visible-mark) (40 . helm-prev-visible-mark) (103 keymap (114 . helm-refresh) (103 . helm-beginning-of-buffer) (106 . helm-next-source) (107 . helm-previous-source)) (93 keymap (93 . helm-next-source)) (91 keymap (91 . helm-previous-source)) (tab . helm-select-action) (4 . helm-next-page) (15 . helm-next-source) (14 . helm-next-line) (16 . helm-previous-line) (22 . helm-next-page) (13 . helm-maybe-exit-minibuffer) (2 . helm-previous-page) (6 . helm-next-page) (27 keymap (118 . helm-previous-page) (107 . helm-previous-line) (106 . helm-next-line) (108 . helm-execute-persistent-action) (93 . helm-next-source) (91 . helm-previous-source))) (insert-state keymap "Auxiliary keymap for Insert state" (15 . helm-next-source) (14 . helm-next-line) (16 . helm-previous-line) (22 . helm-next-page) (13 . helm-maybe-exit-minibuffer) (2 . helm-previous-page) (6 . helm-next-page) (27 keymap (118 . helm-previous-page) (107 . helm-previous-line) (106 . helm-next-line) (108 . helm-execute-persistent-action) (93 . helm-next-source) (91 . helm-previous-source))) (\(insert\ normal\)-state keymap "Auxiliary keymap for (insert normal) state") (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 lambda nil (interactive) (helm-select-nth-action 11)) (f11 lambda nil (interactive) (helm-select-nth-action 10)) (f10 lambda nil (interactive) (helm-select-nth-action 9)) (f9 lambda nil (interactive) (helm-select-nth-action 8)) (f8 lambda nil (interactive) (helm-select-nth-action 7)) (f7 lambda nil (interactive) (helm-select-nth-action 6)) (f6 lambda nil (interactive) (helm-select-nth-action 5)) (f5 lambda nil (interactive) (helm-select-nth-action 4)) (f4 lambda nil (interactive) (helm-select-nth-action 3)) (f3 lambda nil (interactive) (helm-select-nth-action 2)) (f2 lambda nil (interactive) (helm-select-nth-action 1)) (menu-bar keymap (help-menu keymap (describe keymap (describe-mode . helm-help)))) (help keymap (109 . helm-help)) (23 . #f(compiled-function () (interactive nil) #<bytecode 0x1577a5c504232439>)) (f1 lambda nil (interactive) (helm-select-nth-action 0)) (8 . helm-next-source) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap (57 . helm-execute-selection-action-at-nth-+9) (56 . helm-execute-selection-action-at-nth-+8) (55 . helm-execute-selection-action-at-nth-+7) (54 . helm-execute-selection-action-at-nth-+6) (53 . helm-execute-selection-action-at-nth-+5) (52 . helm-execute-selection-action-at-nth-+4) (51 . helm-execute-selection-action-at-nth-+3) (50 . helm-execute-selection-action-at-nth-+2) (49 . helm-execute-selection-action-at-nth-+1) (63 . helm-help) (110 . #f(compiled-function () (interactive nil) #<bytecode 0x157751f378232439>)) (108 . helm-display-line-numbers-mode) (62 . helm-toggle-truncate-line) (21 . helm-refresh) (6 . helm-follow-mode) (9 . helm-copy-to-buffer) (11 . helm-kill-selection-and-quit) (25 . helm-yank-selection) (37 . helm-exchange-minibuffer-and-header-line) (95 . helm-toggle-full-frame) (45 . helm-swap-windows)) (67108987 . helm-enlarge-window) (67108989 . helm-narrow-window) (19 . undefined) (24 keymap (57 . helm-execute-selection-action-at-nth-+9) (56 . helm-execute-selection-action-at-nth-+8) (55 . helm-execute-selection-action-at-nth-+7) (54 . helm-execute-selection-action-at-nth-+6) (53 . helm-execute-selection-action-at-nth-+5) (52 . helm-execute-selection-action-at-nth-+4) (51 . helm-execute-selection-action-at-nth-+3) (50 . helm-execute-selection-action-at-nth-+2) (49 . helm-execute-selection-action-at-nth-+1) (2 . helm-resume-list-buffers-after-quit) (98 . helm-resume-previous-session-after-quit) (6 . helm-quit-and-find-file)) (11 . helm-previous-line) (67108896 . helm-toggle-visible-mark-forward) (0 . helm-toggle-visible-mark) (C-M-up . helm-scroll-other-window-down) (C-M-down . helm-scroll-other-window) (M-prior . helm-scroll-other-window-down) (M-next . helm-scroll-other-window) (12 . helm-recenter-top-bottom-other-window) (15 . helm-next-source) (10 . helm-next-line) (9 . helm-execute-persistent-action) (13 . helm-maybe-exit-minibuffer) (7 . helm-keyboard-quit) ...) nil nil #("helm-treemacs-icons-enable" 0 26 (face highlight-defined-function-name-face fontified t)) t)
  helm-read-pattern-maybe(nil nil nil nil nil nil nil)
  helm-internal((helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found) nil nil nil nil "*helm mini*" nil nil nil)
  apply(helm-internal ((helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found) nil nil nil nil "*helm mini*" nil nil nil))
  helm((helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found) nil nil nil nil "*helm mini*" nil nil nil)
  apply(helm ((helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found) nil nil nil nil "*helm mini*" nil nil nil))
  helm(:sources (helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found) :buffer "*helm mini*" :ff-transformer-show-only-basename nil :truncate-lines t :left-margin-width 0)
  helm-mini()
  funcall-interactively(helm-mini)
  call-interactively(helm-mini nil nil)
  command-execute(helm-mini)

```

With helm-treemacs-icons disabled, this does not happen.
Marking single candidates with "C-SPC" works fine with helm-treemacs-icons.

**Comment by yyoncho** [comment]
hi @thierryvolpiatto , apparently prepending icon in the candidates breaks the mark all functionality which checks if 'display property is `[?]` in order to avoid selecting the candidate. Since I cannot preserve the `display` property because effectively it is used to display the image I would propose `helm` to be changed to use different text property e. g. `helm-skip-mark-all`. WDYT?

**Comment by yyoncho** [comment]
FTR helm breaks even without using helm-treemacs-icons, e. g.

```
(helm :sources (helm-build-sync-source "test"
                 :candidates `(#("  " 0 1
                                 (display
                                  (image :type png :file "" :scale 1 :ascent center :background "#292b2e" :height 14 :width 14))) 
                               "second"))
      :buffer "*helm test*")
```

... and then `M-A` throws the same error.

**Comment by thierryvolpiatto** [comment]
Ivan Yonchovski <notifications@github.com> writes:

> FTR helm breaks even without using helm-treemacs-icons, e. g.
>
> (helm :sources (helm-build-sync-source "test"
>                  :candidates `(#("  " 0 1
>                                  (display
>                                   (image :type png :file "" :scale 1 :ascent center :background "#292b2e" :height 14 :width 14))) 
>                                "second"))
>       :buffer "*helm test*")
>
> ... and then M-A throws the same error.

Thanks, should be fixed.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by yyoncho** [comment]
Just for the record, with the current fix `M-A` will select also the `[?]`. I am not sure if it is a desired effect. I am marking this as fixed - if we decide to fix the aforementioned issue it will be tracked separately.

**Comment by thierryvolpiatto** [comment]
Ivan Yonchovski <notifications@github.com> writes:

> Just for the record, with the current fix M-A will select also the
> [?].

Not here with emacs-helm.sh, but yes in your recipe, I guess it is
because you replace "[?]" by an image? 

> I am not sure if it is a desired effect.

No it is not.

> I am marking this as fixed - if we decide to fix the aforementioned
> issue it will be tracked separately.

Please report a new issue on helm.

Thanks.



-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Should be fixed as well now, let me know.
Thanks.

**Comment by yyoncho** [comment]
@thierryvolpiatto atm when using M-M in combination with helm-treemacs-icons no items are selected: Here it is proposed fix. 


``` diff
                             ;; https://github.com/yyoncho/helm-treemacs-icons/issues/5
                             ;; and also issue #2296. 
                             (equal prefix "[?]")
-                            ;; Prefix is non-nil (an image?) and not a string.
-                            (and prefix (not (stringp prefix)))
                             (and filecomp-p
                                  (or
                                   ;; autosave files
                                   (string-match-p "\\`[.]?#.*#?\\'" bn)
+                                  (not (file-exists-p bn))
                                   ;; dot files
                                   (member bn '("." ".."))
                                   ;; We need to test here when not using
```

**Comment by thierryvolpiatto** [comment]
Ivan Yonchovski <notifications@github.com> writes:

> @thierryvolpiatto atm when using M-M in combination with helm-treemacs-icons no items are selected: Here it is proposed fix.
>
>                              ;; https://github.com/yyoncho/helm-treemacs-icons/issues/5
>                              ;; and also issue #2296. 
>                              (equal prefix "[?]")
> -                            ;; Prefix is non-nil (an image?) and not a string.
> -                            (and prefix (not (stringp prefix)))
>                              (and filecomp-p
>                                   (or
>                                    ;; autosave files
>                                    (string-match-p "\\`[.]?#.*#?\\'" bn)
> +                                  (not (file-exists-p bn))

I prefer not using file-exists-p here, it is terribly costly when
marking all files in a large directory, this remind me I can remove the
next test for remote files which is nowaday unneeded.

> 
>                                    ;; dot files (member bn '("."
> ".."))  ;; We need to test here when not using
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Ivan Yonchovski <notifications@github.com> writes:

> @thierryvolpiatto atm when using M-M in combination with helm-treemacs-icons no items are selected: Here it is proposed fix.
>
>                              ;; https://github.com/yyoncho/helm-treemacs-icons/issues/5
>                              ;; and also issue #2296. 
>                              (equal prefix "[?]")
> -                            ;; Prefix is non-nil (an image?) and not a string.
> -                            (and prefix (not (stringp prefix)))
>                              (and filecomp-p
>                                   (or
>                                    ;; autosave files
>                                    (string-match-p "\\`[.]?#.*#?\\'" bn)
> +                                  (not (file-exists-p bn))
>                                    ;; dot files
>                                    (member bn '("." ".."))
>                                    ;; We need to test here when not using

Here what I propose:

1) I install this patch for helm-mark-all-1:

@@ -6829 +6829 @@ is not needed."
-                            (and prefix (not (stringp prefix)))
+                            ;; (and prefix (not (stringp prefix)))

2) You install this change (or something like this) in H-T-icons:

    (defun helm-treemacs-icons-files-add-icons (candidates _source)
      "Add icon to files source.
    CANDIDATES is the list of candidates."
      (-map (-lambda (candidate)
              (-let [(display . file-name) (if (listp candidate)
                                               candidate
                                             (cons candidate candidate))]
                (cons (if (equal (get-text-property 0 'display display) "[?]")
                          display
                        (concat (cond
                                 ((f-dir? file-name) (helm-treemacs-icons--get-icon 'dir-open))
                                 ((helm-treemacs-icons--get-icon (f-ext file-name)))
                                 ((helm-treemacs-icons--get-icon 'fallback)))
                                display))
                      file-name)))
            candidates))


WDYT?

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by yyoncho** [comment]
This is definitely one of the options. Alternatively, I may put some kind of marker in the image which you can then check in helm. I like the way the icon is updated as you type the file extension - it feels like a polished product, but I am fine also with the proposed solution.

**Comment by yyoncho** [comment]
One more option: 

1. As you have described in https://github.com/yyoncho/helm-treemacs-icons/issues/5#issuecomment-621231459
2. I change helm-t-i to insert the image after `[?]`

**Comment by thierryvolpiatto** [comment]
Ivan Yonchovski <notifications@github.com> writes:

> This is definitely one of the options. Alternatively, I may put some kind of marker in the image which you can then check in helm. I like the way the icon is updated as
> you type the file extension - it feels like a polished product, but I
> am fine also with the proposed solution.

Ok, let me know if you want me to make the change described in 1).

Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by yyoncho** [comment]
@thierryvolpiatto go ahead and I will adjust helm-treemacs-icons. Thank you.

**Comment by thierryvolpiatto** [comment]
Ivan Yonchovski <notifications@github.com> writes:

> @thierryvolpiatto go ahead and I will adjust helm-treemacs-icons.

Done, thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
