### ISSUE TITLE
wrong icones before activating treemacs

### ISSUE THREAD

**Issue by lcacciari** [yyoncho/helm-icons#9]
After starting emacs, commands like helm-find-file display the "wrong" icons (thy have a white backdrop, for one). Once I activate treemacs in the frame by executing M-x treemacs the icons used in helm-find-file change to what I was expecting (the same shown in the treemacs tree).

I have some screenshot but I don't know how insert them here

**Comment by yyoncho** [comment]
Isn't that fixed by https://github.com/yyoncho/helm-icons/commit/d8c15dc61c1f321686b447e83abb17e14bc6f1c6 ?

**Comment by lcacciari** [comment]
Nope, But I think it depended on some package loading order issue. I played around a little and now it works. Sorry for inconveniencing you

**Comment by lcacciari** [comment]
Nope, But I think it depended on some package loading order issue. I played around a little and now it works. Sorry for inconveniencing you

**Comment by ghosty141** [comment]
this happens if helm-icons get used before the first use of treemacs. Any idea for a workaround?
